language: node_js
node_js:
  - "0.11"
services:
  - mongodb
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
  - npm install
env:
  - MONGODB_URL=mongodb://127.0.0.1:27017
script:
  - npm start
  - sleep 3
  - casperjs test test/casper.js
